apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    version: "1.0"
    app: home-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-deployment
  template:
    metadata:
      labels:
        app: home-deployment
    spec:
      containers:
      - name: home
        image: jamesmthorne/home:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000