apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    version: "1.0"
    app: home-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-deployment
  template:
    metadata:
      labels:
        app: home-deployment
    spec:
      containers:
      - name: home
        image: jamesmthorne/home:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NR_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: home-secrets
              key: NR_LICENSE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: home-deployment