apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: "false"
spec:
  tls:
  - hosts:
    - api.thorney.me
    secretName: app-web-cert
  rules:
  - host: api.thorney.me
    http:
      paths:
      - path: /
        backend:
          serviceName: home-service
          servicePort: 8080
      - path: /v1/graphql
        backend:
          serviceName: hasura
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-ingress-local
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.192.168.3.254.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: home-service
          servicePort: 8080
      - path: /v1/graphql
        backend:
          serviceName: hasura
          servicePort: 80