apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - api.thorney.me
    secretName: app-web-cert
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: home-service
          servicePort: 8080
      - path: /v1/graphql
        backend:
          serviceName: hasura
          servicePort: 80