apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: home-service
          servicePort: 8080
      - path: /v1/graphql
        backend:
          serviceName: hasura
          servicePort: 80