apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jmthorne101@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: { }
        dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAWYZNRUFBME6HJJ47
            secretAccessKeySecretRef:
              name: home-secrets
              key: AWS_SECRET_ACCESS_KEY
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jmthorne101@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: { }
        dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIAWYZNRUFBME6HJJ47
            secretAccessKeySecretRef:
              name: home-secrets
              key: AWS_SECRET_ACCESS_KEY