apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storageclass
  labels:
    app: postgres
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  storageClassName: postgres-storageclass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  volumeName: postgres-pv
  storageClassName: postgres-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi